import z from '@deepseek-ai/schemastery';

export const SETTINGS_NAMESPACE = 'jev-context-gate';
export const defaultRules = Object.freeze([
  { id: 'investigate-before-claim', enabled: true, phase: 'before', question: '这项请求是否需要先检查证据，才能判断原因？', context: '不要仅凭截图或描述猜测根因。先检查相关源码、配置、日志或运行证据；尚未核实的判断要明确标为假设。', threshold: 0.8 },
  { id: 'evidence-after-answer', enabled: true, phase: 'after', question: '候选回答是否提出了缺少记录证据支持的原因或完成结论？', context: '提出原因或完成结论前，对照本轮实际收集的证据。证据不足时，明确说明尚未核实；只要存在已获授权的下一步，就继续调查。', threshold: 0.8 },
]);
export const DEFAULT_SETTINGS = { enabled: false, provider: '', model: '', nativeJev: true, beforeEnabled: true, afterEnabled: true, maxContextCharacters: 12000, maxCorrections: 2, rules: [...defaultRules] };
const ruleSchema = z.object({ id: z.string().required(), enabled: z.boolean().default(true), phase: z.union([z.const('before'), z.const('after')]).required(), question: z.string().required(), context: z.string().required(), threshold: z.number().min(0).max(1).default(0.8) });
export const SettingsSchema = z.transform(z.object({ enabled: z.boolean().default(false), provider: z.string().default(''), model: z.string().default(''), nativeJev: z.boolean().default(true), beforeEnabled: z.boolean().default(true), afterEnabled: z.boolean().default(true), maxContextCharacters: z.number().step(1).min(0).max(64000).default(12000), maxCorrections: z.number().step(1).min(0).max(8).default(2), rules: z.array(ruleSchema).default([...defaultRules]) }), value => { const rules = value.rules; if (!Array.isArray(rules) || rules.length > 64) throw new TypeError('Expected at most 64 rules'); const ids = new Set(); for (const rule of rules) { if (!rule || typeof rule.id !== 'string' || !/^[a-z][a-z0-9-]{0,63}$/.test(rule.id) || ids.has(rule.id)) throw new TypeError('Invalid or duplicate rule id'); ids.add(rule.id); if (!['before', 'after'].includes(rule.phase)) throw new TypeError('Invalid phase'); if (typeof rule.enabled !== 'boolean') throw new TypeError('Expected enabled boolean'); for (const key of ['question', 'context']) if (typeof rule[key] !== 'string' || !rule[key].trim() || rule[key].length > 8000) throw new TypeError('Invalid '+key); if (!Number.isFinite(rule.threshold) || rule.threshold < 0 || rule.threshold > 1) throw new TypeError('Invalid threshold'); } return { ...value, rules: structuredClone(rules) }; });
export const Config = z.object({ enabled: z.boolean().default(false), provider: z.string().default(''), model: z.string().default(''), nativeJev: z.boolean().default(true), beforeEnabled: z.boolean().default(true), afterEnabled: z.boolean().default(true), maxContextCharacters: z.number().step(1).min(0).max(64000).default(12000), maxCorrections: z.number().step(1).min(0).max(8).default(2), rules: z.array(ruleSchema).default([...defaultRules]) });
